---

- name: Make list of all std services
  set_fact:
    fixed_services: [ "crond", "mysqld" ]

- name: Make list of postgres service
  set_fact:
    postgres_service: "{{ postgres_present | bool | ternary([ \"postgresql-\" + (postgres_version | string) ], []) }}"

- name: Make list of all services
  set_fact:
    all_services: "{{ fixed_services }} + {{ postgres_service }}"

- name: Make list for starting services
  set_fact:
    services: "{{ all_services }}"
  when: state != "stopped"

- name: Make list for stopping services
  set_fact:
    services: "{{ all_services | reverse | list }} + [ 'httpd' ]"
  when: state == "stopped"

- name: Start/stop services
  service:
    name: "{{ item }}"
    state: "{{ state }}"
  with_items: "{{ services }}"

- name: Start/stop ssh server on passive
  service:
    name: "sshd"
    state: "{{ state }}"
  when: server_mode == "passive"

