---

- name: Make list of all services
  set_fact:
    all_services: "[ \"ntpd\", \"crond\", \"mysqld\" ] + {{ postgres_present|ternary([ \"postgresql-{{ postgres_version }}\" ], []) }} ]"

- name: Make list for starting services
  set_fact:
    services: "{{ all_services }}"
  when: state != "stopped"

- name: Make list for stopping services
  set_fact:
    services: "{{ all_services | reverse | list }}"
  when: state == "stopped"

- name: Start/stop services
  service:
    name: "{{ item }}"
    state: "{{ state }}"
  with_items: "{{ services }}"
  ignore_errors: true

- name: Start/stop ssh server on passive
  service:
    name: "sshd"
    state: "{{ state }}"
  when: server_mode == "passive"

