---

- hosts: localhost
  connection: local
  vars:
    - server_mode: "{{ lookup('env', 'BAHMNI_SERVER_MODE') }}"
    - postgres_present: "{{ lookup('env', 'BAHMNI_POSTGRES_PRESENT') }}"
    - setup_replication: "{{ lookup('env', 'BAHMNI_SETUP_REPLICATION') }}"
    - bahmni_replication_username: "{{ lookup('env', 'BAHMNI_REPLICATION_USERNAME') }}"
    - bahmni_replication_password: "{{ lookup('env', 'BAHMNI_REPLICATION_PASSWORD') }}"
    - active_host: "{{ lookup('env', 'BAHMNI_ACTIVE_HOST') }}"
    - passive_host: "{{ lookup('env', 'BAHMNI_PASSIVE_HOST') }}"
  vars_files:
    - variables.yml
    - variables_private.yml
  roles:
    - { role: manage_services, state: started }
    - { role: mysql-replication, when: setup_replication|bool }
    - { role: postgres, restart: true, when: postgres_present|bool }
    - { role: postgres-replication, when: setup_replication|bool and postgres_present|bool }
    - reset_search_index

