---

- hosts: localhost
  connection: local
  vars:
    - server_mode: "{{ lookup('env', 'BAHMNI_SERVER_MODE') }}"
    - bahmni_openelis_enabled: "{{ lookup('env', 'BAHMNI_OPENELIS_ENABLED') }}"
    - setup_replication: "{{ lookup('env', 'BAHMNI_SETUP_REPLICATION') }}"
    - bahmni_replication_username: "{{ lookup('env', 'BAHMNI_REPLICATION_USERNAME') }}"
    - bahmni_replication_password: "{{ lookup('env', 'BAHMNI_REPLICATION_PASSWORD') }}"
    - active_host: "{{ lookup('env', 'BAHMNI_ACTIVE_HOST') }}"
    - passive_host: "{{ lookup('env', 'BAHMNI_PASSIVE_HOST') }}"
  vars_files:
    - variables.yml
  roles:
    - { role: manage_services, state: started }
    - { role: mysql-replication, when: setup_replication|bool }
    - { role: postgres, restart: true, when: bahmni_openelis_enabled|bool }
    - { role: postgres-replication, when: setup_replication|bool and bahmni_openelis_enabled|bool }
    - { role: reset_search_index, when: server_mode == "active" }
    - bahmni_home

