---

- hosts: localhost
  connection: local
  vars:
    - bahmni_openelis_enabled: "{{ lookup('env', 'BAHMNI_OPENELIS_ENABLED') }}"
    - bahmni_implementation_name: "{{ lookup('env', 'BAHMNI_IMPL_NAME') }}"
    - bahmni_implementation_repo: "{{ lookup('env', 'BAHMNI_IMPLEMENTATION_REPO') }}"
    - bahmni_implementation_branch: "{{ lookup('env', 'BAHMNI_IMPLEMENTATION_BRANCH') }}"
  vars_files:
    - variables.yml
  roles:
    - ansible_config
    - configure
    - icon
    - copy_omods
    - sshd_config
    - backup_config
    - { role: postgres, when: bahmni_openelis_enabled|bool }
    - permissions
    - security_patch

