---

- hosts: localhost
  connection: local
  vars:
    - postgres_present: "{{ lookup('env', 'BAHMNI_POSTGRES_PRESENT') }}"
    - bahmni_implementation_name: "{{ lookup('env', 'BAHMNI_IMPL_NAME') }}"
    - bahmni_implementation_repo: "{{ lookup('env', 'BAHMNI_IMPLEMENTATION_REPO') }}"
    - bahmni_implementation_branch: "{{ lookup('env', 'BAHMNI_IMPLEMENTATION_BRANCH') }}"
    - active_host: "{{ lookup('env', 'BAHMNI_ACTIVE_HOST') }}"
    - passive_host: "{{ lookup('env', 'BAHMNI_PASSIVE_HOST') }}"
    - nestor_host: "{{ lookup('env', 'BAHMNI_NESTOR_HOST') }}"
  vars_files:
    - variables.yml
    - variables_private.yml
  roles:
    - ansible_config
    - configure
    - icon
    - copy_omods
    - sshd_config
    - { role: backup_config, when: bahmni_backup|default(false)|bool }
    - { role: postgres, when: postgres_present|bool }
    - permissions

