---

- hosts: localhost
  connection: local
  vars_files:
    - variables.yml
    - variables_private.yml
  roles:
    - sshd_config
    - { role: backup_config, when: bahmni_backup|default(false)|bool }

