---

- name: Unlock root account
  user:
    name: root
    password: '*'
    state: present

- name: Create ssh dir for root
  file:
    path: "/root/.ssh/"
    recurse: yes
    state: directory

- name: Synchronize ssh keys for root
  synchronize:
    src: "/tmp/artifacts/keys/"
    dest: "/root/.ssh/"
    checksum: yes

- name: Set ssh key permissions for root
  file:
    path: "/root/.ssh/{{ item }}"
    mode: 0600
  with_items:
    - bahmni_key
    - bahmni_key.pub

- name: Create the authorized_keys file
  copy:
    src: "/root/.ssh/bahmni_key.pub"
    dest: "/root/.ssh/authorized_keys"
    mode: "0600"

- name: SSHd config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config

