---

- name: Reset OpenMRS search index
  shell: "mysql -uroot -p{{ mysql_root_password }} -e \"update global_property set property_value = '' where property = 'search.indexVersion';\" openmrs"
  ignore_errors: true

#- name: Reset LiquiBase changelog lock
#  shell: "mysql -uroot -p{{ mysql_root_password }} -e \"update  = '' where property = 'search.indexVersion';\" openmrs"
#  ignore_errors: true

