---

- hosts: localhost
  connection: local
  vars_files:
    - variables.yml
    - variables_private.yml
    - "variables_{{ lookup('env', 'impl_file_suffix') }}.yml"
  roles:
    - fix_python
    - setup_installer
    - { role: backup_config, when: bahmni_backup|default(false)|bool }

