---

- name: Create /bahmni_backup dir
  file:
    path: "{{ bahmni_backup_dir }}/backups"
    recurse: yes
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: Synchronize the backup scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ bahmni_backup_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0700"
  with_items:
    - backup.sh
    - move_backup_to_passive.sh
    - move_backup_to_nestor.sh

- name: Start cron service
  service:
    name: crond
    state: started

# Backup locally every day every three hours at the hour (00 */3)
- name: Configure local backup cronjob
  cron:
    name: local backup
    hour: "*/3"
    minute: "00"
    weekday: "1,2,3,4,5,6,0"
    job: "{{ bahmni_backup_dir }}/backup.sh 2>&1 | tee {{ bahmni_backup_dir }}/last.log > /dev/null"

# Backup to passive every day every three hours at the half hour (30 */3)
- name: Configure passive backup cronjob
  cron:
    name: passive backup
    hour: "*/3"
    minute: "30"
    weekday: "1,2,3,4,5,6,0"
    job: "{{ bahmni_backup_dir }}/move_backup_to_passive.sh 2>&1 | tee -a {{ bahmni_backup_dir }}/last.log > /dev/null"

# Backup to nestor every day every three hours at the half hour (30 */3)
- name: Configure nestor backup cronjob
  cron:
    name: nestor backup
    hour: "*/3"
    minute: "30"
    weekday: "1,2,3,4,5,6,0"
    job: "{{ bahmni_backup_dir }}/move_backup_to_nestor.sh 2>&1 | tee -a {{ bahmni_backup_dir }}/last.log > /dev/null"

# Cleanup old backups daily at 4 in the night (0 4)
- name: Configure backup cleanup cronjob
  cron:
    name: backup cleanup
    hour: "4"
    minute: "0"
    weekday: "1,2,3,4,5,6,0"
    job: "/bin/find {{ bahmni_backup_dir }}/backups/ -mtime +30 -exec rm -rf {} \\; > /dev/null 2>&1"

