---

- name: Install python-setuptools
  yum:
    name: python-setuptools
    state: present

- name: Install the Bahmni installer
  yum:
    name: "{{ bahmni_installer_url }}"
    state: present

- name: Synchronize the default setup file
  template:
    src: "default-setup.j2"
    dest: "/etc/bahmni-installer/setup.yml"

- name: Synchronize the inventory file
  template:
    src: "inventory"
    dest: "/etc/bahmni-installer/local"

- name: Create directory for deployment artifacts
  file:
    path: "/etc/bahmni-installer/deployment-artifacts/"
    recurse: yes
    state: directory

- name: Create an empty config
  file:
    path: "/etc/bahmni-installer/deployment-artifacts/{{ bahmni_implementation_name }}_config"
    state: directory

- name: Copy the Bahmni playbooks
  synchronize:
    src: "/tmp/artifacts/bahmni-playbooks/"
    dest: "/opt/bahmni-installer/bahmni-playbooks"
    delete: no
    rsync_opts:
      - "--exclude=.git/"
    copy_links: yes
    checksum: yes

# See pull request @ https://github.com/Bahmni/bahmni-playbooks/pull/6
- name: Remove ProxyPreserveHost directive
  lineinfile:
    path: "/opt/bahmni-installer/bahmni-playbooks/roles/bahmni-web/templates/ssl.conf.j2"
    regexp: "ProxyPreserveHost On"
    state: absent

