---

- name: Install python-setuptools
  yum:
    name: python-setuptools
    state: present

- name: Install the Bahmni installer
  yum:
    name: "{{ bahmni_installer_url }}"
    state: present

- name: Synchronize the default setup file
  template:
    src: "default-setup.j2"
    dest: "/etc/bahmni-installer/setup.yml"

- name: Synchronize the inventory file
  template:
    src: "inventory"
    dest: "/etc/bahmni-installer/local"

- name: Create directory for deployment artifacts
  file:
    path: "/etc/bahmni-installer/deployment-artifacts/"
    recurse: yes
    state: directory

- name: Create an empty config
  file:
    path: "/etc/bahmni-installer/deployment-artifacts/{{ bahmni_implementation_name }}_config"
    state: directory

- name: Copy the Bahmni playbooks
  synchronize:
    src: "/tmp/artifacts/bahmni-playbooks/"
    dest: "/opt/bahmni-installer/bahmni-playbooks"
    delete: no
    rsync_opts:
      - "--exclude=.git/"
    copy_links: yes
    checksum: yes

- name: Replace report user ID
  replace:
    path: "/opt/bahmni-installer/bahmni-playbooks/group_vars/local"
    regexp: "openmrs_reporting_user: reports-user"
    replace: "openmrs_reporting_user: {{ lookup('env','BAHMNI_REPORTS_USERNAME') }}"

- name: Replace report user password
  replace:
    path: "/opt/bahmni-installer/bahmni-playbooks/group_vars/local"
    regexp: "openmrs_reporting_password: Admin123"
    replace: "openmrs_reporting_password: {{ lookup('env','BAHMNI_REPORTS_PASSWORD') }}"

# See pull request @ https://github.com/Bahmni/bahmni-playbooks/pull/6
- name: Remove ProxyPreserveHost directive
  lineinfile:
    path: "/opt/bahmni-installer/bahmni-playbooks/roles/bahmni-web/templates/ssl.conf.j2"
    regexp: "ProxyPreserveHost On"
    state: absent

- name: remove click v7.1.2
  pip:
    name: click
    state: absent

- name: install click v7.0
  raw: easy_install --always-unzip --allow-hosts=None /opt/Click-7.0.tar.gz

