---

- name: Create the bahmni-reports dir
  file:
    path: "/home/bahmni/.bahmni-reports"
    owner: bahmni
    group: bahmni
    mode: 0666
    state: directory

- name: Create the bahmni-reports.properties link
  file:
    dest: "/home/bahmni/.bahmni-reports/bahmni-reports.properties"
    src: "/etc/bahmni-reports/bahmni-reports.properties"
    owner: bahmni
    group: bahmni
    state: link

