---

- hosts: localhost
  connection: local
  vars:
    - bahmni_installer_url: "{{ lookup('env', 'BAHMNI_INSTALLER_URL') }}"
    - bahmni_implementation_name: "{{ lookup('env', 'BAHMNI_IMPL_NAME') }}"
    - bahmni_timezone: "{{ lookup('env', 'BAHMNI_TIMEZONE') }}"
    - bahmni_openelis_enabled: "{{ lookup('env', 'BAHMNI_OPENELIS_ENABLED') }}"
    - bahmni_reports_enabled: "{{ lookup('env', 'BAHMNI_REPORTS_ENABLED') }}"
    - bahmni_openmrs_username: "{{ lookup('env', 'BAHMNI_OPENMRS_USERNAME') }}"
    - bahmni_openmrs_password: "{{ lookup('env', 'BAHMNI_OPENMRS_PASSWORD') }}"
    - bahmni_openelis_username: "{{ lookup('env', 'BAHMNI_OPENELIS_USERNAME') }}"
    - bahmni_openelis_password: "{{ lookup('env', 'BAHMNI_OPENELIS_PASSWORD') }}"
    - bahmni_reports_username: "{{ lookup('env', 'BAHMNI_REPORTS_USERNAME') }}"
    - bahmni_reports_password: "{{ lookup('env', 'BAHMNI_REPORTS_PASSWORD') }}"
  vars_files:
    - variables.yml
  roles:
    - fix_python
    - setup_installer

