---

- hosts: localhost
  connection: local
  vars:
    - bahmni_installer_url: "{{ lookup('env', 'BAHMNI_INSTALLER_URL') }}"
    - bahmni_implementation_name: "{{ lookup('env', 'BAHMNI_IMPL_NAME') }}"
    - bahmni_timezone: "{{ lookup('env', 'BAHMNI_TIMEZONE') }}"
  vars_files:
    - variables.yml
    - variables_private.yml
  roles:
    - fix_python
    - setup_installer

