---

- hosts: localhost
  connection: local
  vars:
    server_mode: "{{ lookup('env', 'BAHMNI_SERVER_MODE') }}"
    postgres_present: "{{ lookup('env', 'BAHMNI_POSTGRES_PRESENT') }}"
  vars_files:
    - variables.yml
    - variables_private.yml
  roles:
      - { role: manage_services, state: stopped }

