---

- name: Do not gather hardware facts to avoid a bug with Ansible on Docker
  lineinfile:
    path: "{{ item }}"
    insertafter: "^#?gather_subset"
    line: "gather_subset = !hardware"
  with_items:
    - /etc/ansible/ansible.cfg
    - /opt/bahmni-installer/bahmni-playbooks/ansible.cfg

