---

- name: Create ssh dir for root
  file:
    path: "/root/.ssh/"
    recurse: yes
    state: directory

- name: Synchronize ssh keys for root
  synchronize:
    src: "/tmp/artifacts/keys/"
    dest: "/root/.ssh/"
    checksum: yes

- name: Set ssh key permissions for root
  file:
    path: "/root/.ssh/{{ item }}"
    mode: 0600
  with_items:
    - bahmni_key
    - bahmni_key.pub

- name: Create the authorized_keys file
  copy:
    src: "/root/.ssh/bahmni_key.pub"
    dest: "/root/.ssh/authorized_keys"
    mode: "0600"

- name: SSHd config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }
    - { regexp: "^GatewayPorts", line: "GatewayPorts no" }
    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regexp: "^ChallengeResponseAuthentication", line: "ChallengeResponseAuthentication no" }
    - { regexp: "^UsePAM", line: "UsePAM yes" }
    - { regexp: "^Protocol", line: "Protocol 2" }
    - { regexp: "^X11Forwarding", line: "X11Forwarding no" }

- name: Create /bahmni_backup dir
  file:
    path: "{{ bahmni_backup_dir }}/backups"
    recurse: yes
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: Synchronize the backup scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ bahmni_backup_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0700"
  with_items:
    - backup.sh
    - move_backup_to_passive.sh
    - move_backup_to_nestor.sh

- name: Start cron service
  service:
    name: crond
    state: started

# Backup locally every day every three hours at the hour (00 */3)
- name: Configure local backup cronjob
  cron:
    name: local backup
    hour: "*/3"
    minute: "00"
    weekday: "1,2,3,4,5,6,0"
    job: "{{ bahmni_backup_dir }}/backup.sh 2>&1 | tee {{ bahmni_backup_dir }}/last.log > /dev/null"

# Backup to passive every day every three hours at the half hour (30 */3)
- name: Configure passive backup cronjob
  cron:
    name: passive backup
    hour: "*/3"
    minute: "30"
    weekday: "1,2,3,4,5,6,0"
    job: "{{ bahmni_backup_dir }}/move_backup_to_passive.sh 2>&1 | tee -a {{ bahmni_backup_dir }}/last.log > /dev/null"

# Backup to nestor every day every three hours at the half hour (30 */3)
- name: Configure nestor backup cronjob
  cron:
    name: nestor backup
    hour: "*/3"
    minute: "30"
    weekday: "1,2,3,4,5,6,0"
    job: "{{ bahmni_backup_dir }}/move_backup_to_nestor.sh 2>&1 | tee -a {{ bahmni_backup_dir }}/last.log > /dev/null"

# Cleanup old backups daily at 4 in the night (0 4)
- name: Configure backup cleanup cronjob
  cron:
    name: backup cleanup
    hour: "4"
    minute: "0"
    weekday: "1,2,3,4,5,6,0"
    job: "/bin/find {{ bahmni_backup_dir }}/backups/ -mtime +30 -exec rm -rf {} \\; > /dev/null 2>&1"

# Cleanup backups log file weekly at 5h30 in the night on Saturday (30 5)
- name: Configure backup logfile cleanup cronjob
  cron:
    name: backup logfile cleanup
    hour: "5"
    minute: "30"
    weekday: "6"
    job: "tail -300 {{ bahmni_backup_dir }}/last.log | tee {{ bahmni_backup_dir }}/last.log > /dev/null"

