---

- name: Create /bahmni_backup dir
  file:
    path: "{{ bahmni_backup_dir }}/backups"
    recurse: yes
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: Synchronize the backup scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ bahmni_backup_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0700"
  with_items:
    - backup.sh

- name: Start cron service
  service:
    name: crond
    state: started

# Backup locally every day every three hours at the hour (00 */3)
- name: Configure local backup cronjob
  cron:
    name: local backup
    hour: "*/3"
    minute: "00"
    weekday: "*"
    job: "{{ bahmni_backup_dir }}/backup.sh 2>&1 | tee -a {{ bahmni_backup_dir }}/last.log > /dev/null"

# Cleanup backups log file weekly at 5h30 in the night on Saturday (30 5)
- name: Configure backup logfile cleanup cronjob
  cron:
    name: backup logfile cleanup
    hour: "5"
    minute: "30"
    weekday: "6"
    job: "tail -300 {{ bahmni_backup_dir }}/last.log | tee {{ bahmni_backup_dir }}/last.log > /dev/null"

