---

- name: Remove the old omod
  file:
    path: /opt/openmrs/modules/webservices.rest-2.20.0.omod
    state: absent

- name: Put the new omod in place
  copy:
    src: /tmp/webservices.rest-2.24.0.omod
    dest: /opt/openmrs/modules
    owner: bahmni
    group: bahmni
    mode: 0400

