---

- name: Install the Bahmni installer
  yum:
    name: "https://dl.bintray.com/bahmni/rpm/rpms/bahmni-installer-0.90-291.noarch.rpm"
    state: present

- name: Copy the MSF logo
  copy:
    src: msf_logo.png
    dest: /msf_logo.png

- name: Synchronize the certs directory
  synchronize:
    src: "/tmp/artifacts/certs/"
    dest: "{{ bahmni_cert_dir }}"
    checksum: yes

- name: Create the authorized_keys file
  copy:
    src: "/root/.ssh/bahmni_key.pub"
    dest: "/root/.ssh/authorized_keys"
    mode: "0600"

- name: Synchronize the misc files
  synchronize:
    src: "/tmp/artifacts/misc/"
    dest: "/tmp/"
    perms: no  # Don't change perms of /tmp
    copy_links: yes
    checksum: yes

- name: Synchronize the default setup file
  template:
    src: "default-setup.j2"
    dest: "/etc/bahmni-installer/setup.yml"

- name: Synchronize the inventory file
  copy:
    src: /inventory
    dest: /etc/bahmni-installer/local

- name: Create directory for deployment artifacts
  file:
    path: "/etc/bahmni-installer/deployment-artifacts/"
    recurse: yes
    state: directory

- name: Clone the Bahmni config
  git:
    repo: "https://github.com/OCB-MSF/ocb-config.git"
    dest: "/etc/bahmni-installer/deployment-artifacts/{{ bahmni_implementation_name }}_config"
    clone: yes
    update: yes
    version: "{{ bahmni_implementation_branch }}"
    depth: 1
    force: yes

- name: Delete Git info from Bahmni config
  file:
    path: "/etc/bahmni-installer/deployment-artifacts/{{ bahmni_implementation_name }}_config/.git"
    state: absent

- name: Copy the OpenMRS SQL dump
  synchronize:
    src: "/etc/bahmni-installer/deployment-artifacts/{{ bahmni_implementation_name }}_config/db_dumps/openmrs_backup.sql"
    dest: "/etc/bahmni-installer/deployment-artifacts/openmrs_backup.sql"
    copy_links: yes
    checksum: yes
  when: copy_sql_dump|default(true)|bool

- name: Copy the OpenELIS SQL dump
  synchronize:
    src: "/etc/bahmni-installer/deployment-artifacts/{{ bahmni_implementation_name }}_config/db_dumps/openelis_backup.sql"
    dest: "/etc/bahmni-installer/deployment-artifacts/openelis_backup.sql"
    copy_links: yes
    checksum: yes
  when: copy_sql_dump|default(true)|bool

- name: Copy the Bahmni playbooks
  synchronize:
    src: "/tmp/artifacts/bahmni-playbooks/"
    dest: "/opt/bahmni-installer/bahmni-playbooks"
    delete: no
    rsync_opts:
      - "--exclude=.git/"
    copy_links: yes
    checksum: yes

# See pull request @ https://github.com/Bahmni/bahmni-playbooks/pull/6
- name: Remove ProxyPreserveHost directive
  lineinfile:
    path: "/opt/bahmni-installer/bahmni-playbooks/roles/bahmni-web/templates/ssl.conf.j2"
    regexp: "ProxyPreserveHost On"
    state: absent

