---

- name: Install Bahmni
  command: bahmni -i local install

- name: impl playbooks
  command: bahmni -i local --implementation_play=/var/www/bahmni_config/playbooks/all.yml install-impl

#- name: Setup MySQL replication
#  command: bahmni -i local setup-mysql-replication

#- name: Setup PostgreSQL replication
#  command: bahmni -i local setup-postgres-replication

