---

- name: Create /bahmni_backup dir
  file:
    path: "{{ bahmni_backup_dir }}"
    recurse: yes
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: Create bahmni backup encryption password file
  copy:
    content: "{{ bahmni_backup_enc_password }}"
    dest: "{{ bahmni_backup_enc_password_file }}"
    owner: root
    group: root
    mode: "770"

- name: Synchronize the backup scripts
  template:
    src: "sources/backup_scripts/{{ item }}.j2"
    dest: "{{ bahmni_backup_dir }}/{{ item }}.sh"
    owner: root
    group: root
    mode: "0700"
  with_items:
    - backup
    - move_backup_to_passive
    - move_backup_to_nestor

# Backup to passive every day every three hours at the hour (00 */3)
- name: Configure backup cronjob
  cron:
    name: backup
    hour: "*/3"
    minute: "00"
    weekday: "1,2,3,4,5,6,0"
    job: "{{ bahmni_backup_dir }}/backup.sh 2>&1 | tee {{ bahmni_backup_dir }}/last.log > /dev/null && {{ bahmni_backup_dir }}/move_backup_to_passive.sh 2>&1 | tee -a {{ bahmni_backup_dir }}/last.log > /dev/null"
  when: active

- name: Configure backup cleanup cronjob
  cron:
    name: backup_clean
    hour: "20"
    minute: "0"
    weekday: "1,2,3,4,5"
    job: "/bin/find {{ bahmni_backup_dir }}/backups/ -mtime +30 -exec rm -rf {} \\; > /dev/null 2>&1"
  when: active

