---

- name: Install the needed libraries to do SNI with Python 2.6
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-urllib3
    - pyOpenSSL

# https://stackoverflow.com/questions/26279207/installing-pip-using-easy-install
- name: Fix pypi.python.org url for easy_install
  replace:
    path: /usr/lib/python2.6/site-packages/setuptools/command/easy_install.py
    regexp: "http://pypi.python.org"
    replace: "https://pypi.python.org"

