---

- name: Clone the Bahmni config
  git:
    repo: "{{ bahmni_implementation_repo }}"
    dest: "/etc/bahmni-installer/deployment-artifacts/{{ bahmni_implementation_name }}_config"
    clone: yes
    update: yes
    version: "{{ bahmni_implementation_branch }}"
    depth: 1
    force: yes
    
- name: Register the config commit hash
  command: "git rev-parse HEAD"
  register: config_commit_hash
  
- name: Write the config commit hash to a file
  copy:
    content: "{{ config_commit_hash }}"
    dest: "/config_commit_hash"

- name: Delete Git info from Bahmni config
  file:
    path: "/etc/bahmni-installer/deployment-artifacts/{{ bahmni_implementation_name }}_config/.git"
    state: absent

- name: Check if bahmni_config/report.html exists
  stat:
    path: "/etc/bahmni-installer/deployment-artifacts/{{ bahmni_implementation_name }}_config/report.html"
  register: report_html_stat

- name: Set owner of bahmni_config/report.html to bahmni
  file:
    path: "/etc/bahmni-installer/deployment-artifacts/{{ bahmni_implementation_name }}_config/report.html"
    owner: bahmni
    group: bahmni
  when: report_html_stat.stat.exists

