---

- name: Add replication user
  postgresql_user:
    login_user: postgres
    name: "{{ bahmni_replication_username }}"
    password: "{{ bahmni_replication_password }}"
    role_attr_flags: REPLICATION,LOGIN
    state: present
  when: server_mode == "active"

- name: Stop PostgreSQL
  service:
    name: "postgresql-{{ postgres_version }}"
    state: "stopped"

- block:

  - name: Removing recovery config file
    file:
      path: "/var/lib/pgsql/{{ postgres_version }}/data/recovery.conf"
      state: absent

  - name: Determine what to add to the pg_hba.conf file
    set_fact:
      pg_hba_passive_host: "{{ passive_host if (not (passive_host | ipaddr)) else passive_host + '/32' }}"

  - name: Add the replication user to pg_hba.conf
    blockinfile:
      path: "/var/lib/pgsql/{{ postgres_version }}/data/pg_hba.conf"
      marker: "# {mark} ANSIBLE MANAGED BLOCK (allow the other server)"
      state: present
      block: |
        host replication {{ bahmni_replication_username }} {{ pg_hba_passive_host }} md5

  when: server_mode == "active"

- block:

  - name: Wait for PostgreSQL to become available on the master
    wait_for:
      host: "{{ active_host }}"
      port: "{{ postgresql_replication_port }}"
      delay: 15
      sleep: 3
      state: started

  - name: Delete old data directory
    file:
      path: "/var/lib/pgsql/{{ postgres_version }}/data"
      state: absent

  - name: Starting base backup as replication user
    shell: "pg_basebackup -h {{ active_host }} -D /var/lib/pgsql/{{ postgres_version }}/data -U{{ bahmni_replication_username }} -v -P --xlog-method=stream"
    environment:
      PGPASSWORD: "{{ bahmni_replication_password }}"
    become: true
    become_user: postgres

  - name: Copy recovery conf file
    template:
      src: "recovery.conf.j2"
      dest: "/var/lib/pgsql/{{ postgres_version }}/data/recovery.conf"
      mode: 0644
      owner: postgres
      group: postgres

  - name: Determine what to add to the pg_hba.conf file
    set_fact:
      pg_hba_active_host: "{{ active_host if (not (active_host | ipaddr)) else active_host + '/32' }}"

  - name: Add the replication user to pg_hba.conf
    blockinfile:
      path: "/var/lib/pgsql/{{ postgres_version }}/data/pg_hba.conf"
      marker: "# {mark} ANSIBLE MANAGED BLOCK (allow the other server)"
      state: present
      block: |
        host replication {{ bahmni_replication_username }} {{ pg_hba_active_host }} md5

  when: server_mode == "passive"

- name: Start PostgreSQL
  service:
    name: "postgresql-{{ postgres_version }}"
    state: "started"

